name: Build and Push Docker image

on:
  push:
    branches:
      - main
      - 'v*'
    tags:
      - 'v*'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tag
        id: tagger
        run: |
          REF="${GITHUB_REF#refs/heads/}" # Strip refs/heads/
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          elif [[ "${REF}" == v* ]]; then
            VERSION="${REF#v}"  # Strip the leading 'v'
            echo "DOCKER_TAG=${VERSION}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=dev" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: patternoss/heimdall:${{ env.DOCKER_TAG }}
